name: Thanatopia
favicon: null
layout_spectrum: 0.99271
typography_spectrum: 0.790088898036629
title: News from Dimmortality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262d30'
    - '#000000'
    - '#ffffff'
    - '#400000'
    - '#d1d0d0'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
